name: todo_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  supabase_flutter: ^2.8.0
  permission_handler: ^11.3.1
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  flutter_svg: ^2.0.14
  validators: ^3.0.0
  flutter_secure_storage: ^9.2.2
  connectivity_plus: ^6.1.0
  shared_preferences: ^2.3.3

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
  - assets/images/logo.png
  - assets/icons/calendar.svg
  - assets/icons/note.svg
  - assets/icons/cele.svg
  - assets/icons/back.svg
  - assets/icons/selectDate.svg
  - assets/icons/selectTime.svg
  - assets/icons/lang.svg
  - assets/icons/signout.svg
  - assets/gifs/loading.gif
