name: todo_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.1-alpha

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  supabase_flutter: ^2.8.0
  permission_handler: ^11.3.1
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  flutter_svg: ^2.0.14
  validators: ^3.0.0
  flutter_secure_storage: ^9.2.2
  connectivity_plus: ^6.1.0
  shared_preferences: ^2.3.3
  dartz: ^0.10.1
  alarm: ^4.1.1
  sqflite: ^2.4.1
  path: ^1.9.0
  device_preview: ^1.2.0
  firebase_core: ^3.8.1
  flutter_gen_runner: ^5.8.0
  flutter_dotenv: ^5.2.1

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/gifs/
    - assets/icons/
    - assets/audios/