import 'dart:ui';

import '../models/note_model.dart';

class Configs {
  //MARK: Network

  static const apiSupabaseBaseUrl = "https://jwtukvndlexkwbqasypb.supabase.co";
  static const apiSubabaseKey =
      "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp3dHVrdm5kbGV4a3dicWFzeXBiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjkxNTY0NjMsImV4cCI6MjA0NDczMjQ2M30.QYFrsRJGoAg1SjKGUImEGg3YAxlIp5IdOvAzK6YABBY";

  //MARK: Categories's Colors
  static Color noteCategoryBackgroundColor = const Color(0xFFDBECF6);
  static Color calendarCategoryBackgroundColor = const Color(0xFFE7E2F3);
  static Color celeCategoryBackgroundColor = const Color(0xFFFEF5D3);

  //MARK: Demo data
  static List<NoteModel> demoNotes = [
    NoteModel(
      id: 1,
      deviceId: "device_001",
      taskTitle: "Buy groceries",
      category: 1,
      content: "Milk, bread, eggs, and cheese",
      status: false,
      date: "2024-11-18",
      time: "",
    ),
    NoteModel(
      id: 2,
      deviceId: "device_002",
      taskTitle: "Meeting with team",
      category: 2,
      content: "Discuss project updates and next steps",
      status: true,
      date: "2024-11-18",
      time: "02:00 PM",
    ),
    NoteModel(
      id: 3,
      deviceId: "device_003",
      taskTitle: "Workout session",
      category: 3,
      content: "Cardio and weight training",
      status: false,
      date: "2024-11-19",
      time: "06:30 AM",
    ),
    NoteModel(
      id: 4,
      deviceId: "device_004",
      taskTitle: "Read a book",
      category: 4,
      content: "Continue reading 'Atomic Habits'",
      status: true,
      date: "2024-11-17",
      time: "08:00 PM",
    ),
    NoteModel(
      id: 5,
      deviceId: "device_005",
      taskTitle: "Doctor's appointment",
      category: 5,
      content: "Annual check-up at the health center",
      status: false,
      date: "2024-11-20",
      time: "09:00 AM",
    ),
    NoteModel(
      id: 1,
      deviceId: "device_001",
      taskTitle: "Buy groceries",
      category: 1,
      content: "Milk, bread, eggs, and cheese",
      status: false,
      date: "2024-11-18",
      time: "10:00 AM",
    ),
    NoteModel(
      id: 2,
      deviceId: "device_002",
      taskTitle: "Meeting with team",
      category: 2,
      content: "Discuss project updates and next steps",
      status: true,
      date: "2024-11-18",
      time: "02:00 PM",
    ),
    NoteModel(
      id: 3,
      deviceId: "device_003",
      taskTitle: "Workout session",
      category: 3,
      content: "Cardio and weight training",
      status: false,
      date: "2024-11-19",
      time: "06:30 AM",
    ),
    NoteModel(
      id: 4,
      deviceId: "device_004",
      taskTitle: "Read a book",
      category: 4,
      content: "Continue reading 'Atomic Habits'",
      status: true,
      date: "2024-11-17",
      time: "08:00 PM",
    ),
    NoteModel(
      id: 5,
      deviceId: "device_005",
      taskTitle: "Doctor's appointment",
      category: 5,
      content: "Annual check-up at the health center",
      status: false,
      date: "2024-11-20",
      time: "",
    ),
    NoteModel(
      id: 1,
      deviceId: "device_001",
      taskTitle: "Buy groceries",
      category: 1,
      content: "Milk, bread, eggs, and cheese",
      status: false,
      date: "2024-11-18",
      time: "10:00 AM",
    ),
    NoteModel(
      id: 2,
      deviceId: "device_002",
      taskTitle: "Meeting with team",
      category: 2,
      content: "Discuss project updates and next steps",
      status: true,
      date: "2024-11-18",
      time: "02:00 PM",
    ),
    NoteModel(
      id: 3,
      deviceId: "device_003",
      taskTitle: "Workout session",
      category: 3,
      content: "Cardio and weight training",
      status: false,
      date: "2024-11-19",
      time: "06:30 AM",
    ),
    NoteModel(
      id: 4,
      deviceId: "device_004",
      taskTitle: "Read a book",
      category: 4,
      content: "Continue reading 'Atomic Habits'",
      status: true,
      date: "2024-11-17",
      time: "08:00 PM",
    ),
    NoteModel(
      id: 5,
      deviceId: "device_005",
      taskTitle: "Doctor's appointment",
      category: 5,
      content: "Annual check-up at the health center",
      status: false,
      date: "2024-11-20",
      time: "09:00 AM",
    ),
    NoteModel(
      id: 1,
      deviceId: "device_001",
      taskTitle: "Buy groceries",
      category: 1,
      content: "Milk, bread, eggs, and cheese",
      status: false,
      date: "2024-11-18",
      time: "10:00 AM",
    ),
    NoteModel(
      id: 2,
      deviceId: "device_002",
      taskTitle: "Meeting with team",
      category: 2,
      content: "Discuss project updates and next steps",
      status: true,
      date: "2024-11-18",
      time: "02:00 PM",
    ),
    NoteModel(
      id: 3,
      deviceId: "device_003",
      taskTitle: "Workout session",
      category: 3,
      content: "Cardio and weight training",
      status: false,
      date: "2024-11-19",
      time: "06:30 AM",
    ),
    NoteModel(
      id: 4,
      deviceId: "device_004",
      taskTitle: "Read a book",
      category: 4,
      content: "Continue reading 'Atomic Habits'",
      status: true,
      date: "2024-11-17",
      time: "08:00 PM",
    ),
    NoteModel(
      id: 5,
      deviceId: "device_005",
      taskTitle: "Doctor's appointment",
      category: 5,
      content: "Annual check-up at the health center",
      status: false,
      date: "2024-11-20",
      time: "09:00 AM",
    ),
  ];
}
